version: "3.9"
   
services:
  web:
    build: .
    container_name: IOT_DASHBOARD_BACKEND_SERVER

    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"

    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: IOT_DASHBOARD_DB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"
